version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.40
    platform: linux/arm64/v8
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "$DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT"
    volumes:
      - ./db:/var/lib/mysql
      - ./backend/dump/:/docker-entrypoint-initdb.d

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - mysqldb
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    environment:
      DATABASE_HOST: mysqldb
    volumes:
      - ./backend:/app
      - /app/node_modules  

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file: ./.env
    environment:
      VITE_API_URL: http://backend:$NODE_DOCKER_PORT
    volumes:
      - ./frontend:/app
      - /app/node_modules  
