version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.40
    platform: linux/x86_64/v8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    ports:
      - "${DATABASE_LOCAL_PORT}:${DATABASE_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql
      - dump_data:/docker-entrypoint-initdb.d

  backend:
    depends_on:
      - mysqldb
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_HOST: "mysqldb"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_PORT: "${DATABASE_DOCKER_PORT}"
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - backend_data:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - frontend_data:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
  dump_data:
  backend_data:
  frontend_data:
