version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.40
    platform: linux/arm64/v8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "${DATABASE_LOCAL_PORT}:${DATABASE_DOCKER_PORT}"
    volumes:
      - /tmp/db:/var/lib/mysql 
      - /tmp/dump:/docker-entrypoint-initdb.d 
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_DOCKER_PORT}
    depends_on:
      - mysqldb
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - /tmp/backend:/app  
      - /tmp/node_modules:/app/node_modules 

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:${NODE_DOCKER_PORT}
    volumes:
      - /tmp/frontend:/app 
      - /tmp/node_modules:/app/node_modules  
