services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - ./db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=$DATABASE_LOCAL_PORT
    stdin_open: true
    tty: true

volumes: 
  db:
